name: pr
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
          cache: 'yarn'
      - run: yarn install
      - run: yarn prettier

  test:
    name: Test on GraphQL ${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graphql_version:
          - 16
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
          cache: 'yarn'
      - name: Downgrade GraphQL v${{matrix.graphql_version}}
        if: ${{matrix.graphql_version != 16}}
        run: node ./scripts/downgrade-graphql-version.js ${{matrix.graphql_version}}
      - run: yarn install
      - run: yarn build
      - run: yarn test
