name: pr
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm prettier

  test:
    name: Test on GraphQL ${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graphql_version:
          - 16
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'
      - name: Downgrade GraphQL v${{matrix.graphql_version}}
        if: ${{matrix.graphql_version != 16}}
        run: node ./scripts/downgrade-graphql-version.js ${{matrix.graphql_version}}
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
